language: php

php:
  - 7.0
  - 7.1

env:
  - FLOW_VERSION="4.0.*" PHPUNIT_VERSION="~5.0"

before_script:
  - ./setup.sh
  - cd Build
script: phpunit -v --debug -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Networkteam.Tika/Tests/Functional
